FROM php:7.4-cli

# Mise à jour des paquets et installation des dépendances
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    default-mysql-client \
    zlib1g-dev \
    libzip-dev

# Configuration et installation des extensions PHP GD
RUN docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install -j$(nproc) gd

# Installation des extensions PHP mysqli, pdo, pdo_mysql, zip
RUN docker-php-ext-install mysqli pdo pdo_mysql zip

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copier le contenu du répertoire actuel dans le répertoire /app/ du conteneur
COPY . /app

# Donner les permissions au dossier /app
RUN chown -R www-data:www-data /app

# Installer les dépendances Composer
WORKDIR /app
RUN composer install

# Définir la commande d'exécution des tests
CMD ["vendor/bin/phpunit", "--configuration", "phpunit.xml"]
