# Utiliser l'image de base PHP CLI
FROM php:8.0-cli

# Installer les extensions nécessaires et Composer
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpng-dev \
    libzip-dev \
    && docker-php-ext-install mysqli pdo_mysql gd zip

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Installer PHPUnit globalement via Composer
RUN composer global require phpunit/phpunit ^9.6 --prefer-source

# Ajouter le répertoire global de Composer au PATH
ENV PATH="$PATH:/root/.composer/vendor/bin"

# Activer le buffering de sortie en PHP
RUN echo "output_buffering = On" >> /usr/local/etc/php/conf.d/docker-php.ini

# Copier le projet dans le conteneur
COPY . /app
WORKDIR /app

# Changer les permissions
RUN chown -R www-data:www-data /app

# Installer les dépendances de l'application
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Commande par défaut pour exécuter les tests
CMD ["./vendor/bin/phpunit"]
