

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./KS_Inventory:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ks
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app-network  

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    networks:
      - app-network
    command: ./vendor/bin/phpunit

networks:
  app-network:
    driver: bridge
