version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ks
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inventory-network

  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - inventory-network

volumes:
  db_data:

networks:
  inventory-network:
