 
name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, zip

    - name: Install dependencies
      run: composer install

    - name: Run tests
      run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        echo "Deploying to server..."
        # Add your deployment commands here
        # For example, using rsync or scp to copy files to the server
        # rsync -avz --delete ./ username@yourserver:/path/to/your/application
