name: CI for KS_Inventory

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Run phpMyAdmin
      run: docker-compose up -d

    - name: Verify phpMyAdmin connection
      run: |
        curl --fail http://localhost:8081 || exit 1

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose down
