name: CI for KS_Inventory

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: ks
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h "127.0.0.1" --silent; then
            echo "MySQL is up and running"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Build Docker image
      run: docker build -t my-app-test .

    - name: Run Docker container
      run: docker run --name ks_inventory_web --network=host my-app-test

    - name: Verify MySQL connection through phpMyAdmin
      run: |
        curl --fail http://localhost:8081 || exit 1
